<a href="https://colab.research.google.com/github/lkhaagii98/Bioinfo1_Project/blob/main/CoLab_TermProj_2023_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 생물정보학 및 실습 1 - Term Project용 Mission 3 환경 셋업

```
생물정보학 및 실습 1
서울대학교 생물정보학전공/생명과학부 2023년 1학기

이 노트북은 Creative Commons BY-SA 조건으로 재사용 가능합니다.
장혜식 <hyeshik@snu.ac.kr>, 서울대학교 생명과학부
```

이 노트북은 Google Colab을 이용해서 Term Project를 할 수 있도록 환경을 준비해 줍니다. 터미널 사용이 원활하지 않은 상태이고, 데이터를 오랫동안 보관하기 어렵기 때문에 되도록 개인용 컴퓨터에서 [Anaconda](https://www.anaconda.com/)나 [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) 등을 설치하고 사용하시는 것이 편하지만, 개인용 컴퓨터 사양이 부족한 경우에는 Google CoLab을 사용할 수도 있습니다. 개인용 컴퓨터를 쓸 때는 Windows에서는 [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10)를 쓰시면 리눅스 커맨드라인 환경을 쓸 수 있습니다. Google Colab은 창을 닫은 후 90분 후, 또는 창을 처음 열고 12시간 후에 환경을 닫아버리기 때문에 매번 실습할 때마다 새로 셋업이 필요합니다. `Runtime->Run All`을 실행해서 전체를 한 번 실행하시면 준비됩니다. 모든 것이 잘 안 되고 뭔가 꼬인 느낌이 강하게 들 때는 `Runtime->Factory reset runtime`을 누르고 새로 시작하시면 될 수도 있습니다.

## Google Drive 마운트

데이터 파일들을 불러오고 저장하기 위해서 Google Drive를 연결합니다. **이번엔 스크립트 파일을 편집해야 하기 때문에 Google Drive 마운트를 하지 않으면 vim등 콘솔에서 쓸 수 있는 에디터를 쓰셔야 합니다.** 화면에 나오는 주소를 눌러서 인증하고 인증 코드를 그 아래에 입력하세요. 그러면 `/contents/drive/MyDrive`에서 자신의 Drive 최상단 폴더가 보입니다. Google CoLab에서 접속하지 않고, 본인 컴퓨터 또는 연구실 워크스테이션 등 다른 컴퓨터를 쓰시는 경우에는 저장공간이 충분하므로 이 부분은 생략하고 지나갑니다.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 실습용 Bioconda 환경 설치하기
Google CoLab에서 접속하지 않고, 본인 컴퓨터 또는 연구실 워크스테이션 등 다른 컴퓨터를 쓰시는 경우에는 따로 실습용 [Bioconda](https://bioconda.github.io/) 환경을 구축해서 이 노트북을 그 환경 안에서 띄우시면 됩니다.

CoLab을 쓰시는 분들은 다음에 따라서 실습용 프로그램들을 쉽게 설치할 수 있도록 [Bioconda](https://bioconda.github.io/) 환경을 만듭니다. 실행하고 진행상황을 관찰하다가 에러로 보이는 것이 있으면 잘 읽어보고 해결합니다.

파이썬 모듈들은 Colab쪽의 파이썬 인터프리터를 바꿀 수 없기 때문에 Conda에 설치하더라도 사용하기 어렵습니다. 파이썬 모듈은 `pip` 명령어로 설치하시면 Colab에서 불러와서 사용할 수 있습니다.

환경 초기화에 관련된 스크립트는 [GitHub 프로젝트](https://github.com/hyeshik/colab-biolab)에 있습니다.

In [2]:
!git clone https://github.com/hyeshik/colab-biolab.git
!cd colab-biolab && bash tools/setup.sh
exec(open('colab-biolab/tools/activate_conda.py').read())

Cloning into 'colab-biolab'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 76 (delta 26), reused 59 (delta 15), pack-reused 0
Unpacking objects: 100% (76/76), 318.14 KiB | 6.49 MiB/s, done.
./
./root/
./root/.bashrc.biolab
./root/.tmux.conf
./root/.profile
./root/.vimrc
./root/.condarc
./root/.bin.priority/
./root/.bin.priority/pip3
./root/.bin.priority/pip
./root/.bin.priority/pip2
--2023-05-18 11:26:15--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73134376 (70M) [application/x-sh]
Saving to: ‘miniconda3.sh’

miniconda3.sh       100%[===================>]  69.75M   281MB/s    in 0.2s

2023-05-18 11:26:15 (281 MB/s) - ‘miniconda3.sh’ saved [73134376/73134376]

PREFIX=/root/conda
Unpacking payload ...

Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: - \ | / done
Executing transaction: \ | / - \ | / - \ | / - \ | / - \ | / done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /root/conda
Activated conda environment `lab'!

설정이 끝났으면, 이제 콘솔을 열어서 터미널로 접속할 수 있는 통로를 열어줍니다.

## 시퀀싱 데이터 다운로드
첫 실습 시간에 데이터 복사를 마쳤으면 이 부분은 생략하고 지나갑니다.

이제 실습 수업에서 필요한 시퀀싱 데이터를 다운로드 받아서 설치합시다. 드라이브 공간만 충분하면 데이터는 계속 저장돼 있기 때문에 학기 전체를 통해서 딱 한 번만 하시면 됩니다. Colab에서는 작업용 데이터를 Google Drive 폴더 아래의 `binfo-datapack1`에 저장합니다. 실습용 데이터는 `/content/drive/MyDrive/binfo1-datapack1`에 풀리게 됩니다.

### (Option 1) Google CoLab에서 접속한 경우
1. [Google Drive 공유폴더](https://drive.google.com/drive/folders/1QBJednh-C7A17PFOlpZHBKyDmBvd6klh?usp=sharing)에 접속합니다.
1. 중간 제목줄의 "binfo1-datapack1 ▾"에서 ▾을 누릅니다.
1. Add shortcut to Drive를 누릅니다.
1. My Drive를 선택해서 ADD SHORTCUT 버튼을 누릅니다.
1. 다음 cell을 실행해서 링크가 제대로 들어왔는지 확인합니다. (바로 확인되지 않으면 3–5분 정도 기다렸다가 하면 됩니다.)
1. 제대로 확인되면 다음으로 넘어갑니다.

In [ ]:
!ls -al /content/drive/MyDrive/binfo1-datapack1/

total 7162852
-r-------- 1 root root 1370036258 Apr 27 14:53 CLIP-35L33G.bam
-r-------- 1 root root    3118336 Apr 27 14:53 CLIP-35L33G.bam.bai
-r-------- 1 root root       7113 May 11 11:02 CLIP-let7g.bam
-r-------- 1 root root      14561 May 11 11:03 CLIP-let7g-gene.pileup
-r-------- 1 root root    2685065 May 11 11:02 CLIP-let7g.pileup
-r-------- 1 root root  883334756 Apr 27 14:53 gencode.gtf
-r-------- 1 root root   24065406 Apr 27 15:15 read-counts.txt
-r-------- 1 root root        751 Apr 27 15:15 read-counts.txt.summary
-r-------- 1 root root 1003658801 Apr 27 14:54 RNA-control.bam
-r-------- 1 root root    2276104 Apr 27 14:53 RNA-control.bam.bai
-r-------- 1 root root 1260991122 Apr 27 14:54 RNA-siLin28a.bam
-r-------- 1 root root    2710744 Apr 27 14:54 RNA-siLin28a.bam.bai
-r-------- 1 root root  981684502 Apr 27 14:54 RNA-siLuc.bam
-r-------- 1 root root    2606104 Apr 27 14:54 RNA-siLuc.bam.bai
-r-------- 1 root root  737352902 Apr 27 14:54 RPF-siLin28a.bam
-r-------- 1 root root    2482768 Apr 27 14:54 RPF-siLin28a.bam.bai
-r-------- 1 root root 1055123479 Apr 27 14:54 RPF-siLuc.bam
-r-------- 1 root root    2605912 Apr 27 14:54 RPF-siLuc.bam.bai

### (Option 2) CoLab외의 다른 환경에서 접속한 경우
본인 컴퓨터나 연구실 워크스테이션 등에서 작업하는 경우에는 다음 명령어로 다운로드 받으시면 됩니다. 첫 번째에는 wget이 접속오류를 내는 경우가 많으니, 접속에러가 발생하면 다시 한 번 실행해 보세요. `/content/drive/Mydrive` 부분은 원하는 저장 경로로 바꿔서 지정하시면 됩니다.

In [ ]:
!wget -O - --no-check-certificate https://hyeshik.qbio.io/binfo/binfo1-datapack1.tar | tar -C /content/drive/MyDrive -xf -

### 파일 체크섬 확인

받은 데이터의 MD5 체크섬을 확인합니다. 한참 걸립니다. 각 파일들의 원래 체크섬은 다음과 같습니다. 한 번 비교해 보세요.

```
140aaf30bcb9276cc716f8699f04ddd6  CLIP-35L33G.bam
f1b3336ed7e2f97d562dcc71641251bd  CLIP-35L33G.bam.bai
328883a73d507eafbf5b60bd6b906201  RNA-control.bam
02073818e2f398a73c3b76e5169de1ca  RNA-control.bam.bai
b09550d09d6c2a4ce27f0226f426fdb1  RNA-siLin28a.bam
fef112c727244060ea62d3f2564a07f6  RNA-siLin28a.bam.bai
28bbd0c47d725669340c784f1b772c01  RNA-siLuc.bam
43590fdc4d81905c0432e0d1cb8cfd5b  RNA-siLuc.bam.bai
5c08a9297307bc83259e658c4474f0cc  RPF-siLin28a.bam
a1bb3e29be412dfd7fd8d16b1b1acc4c  RPF-siLin28a.bam.bai
f2eebf50943024d0116c9cd3e744c707  RPF-siLuc.bam
dc24f69e8f571fc8be30f28ce5b84fcd  RPF-siLuc.bam.bai
```

In [ ]:
!md5sum drive/MyDrive/binfo1-datapack1/*

140aaf30bcb9276cc716f8699f04ddd6  drive/MyDrive/binfo1-datapack1/CLIP-35L33G.bam
f1b3336ed7e2f97d562dcc71641251bd  drive/MyDrive/binfo1-datapack1/CLIP-35L33G.bam.bai
5d0265965487c33475f48869fc9df2d2  drive/MyDrive/binfo1-datapack1/CLIP-let7g.bam
4ea14471c5d4bf9ab1fd91b9a5b2193c  drive/MyDrive/binfo1-datapack1/CLIP-let7g-gene.pileup
a53f66a5575d4ac2d3b4c44af576d44d  drive/MyDrive/binfo1-datapack1/CLIP-let7g.pileup
d54d428f5872030c4ffc43058709b896  drive/MyDrive/binfo1-datapack1/gencode.gtf
2698e6c8e30005ebc0593d3b9e9b5c58  drive/MyDrive/binfo1-datapack1/read-counts.txt
7c9528c08ed2f1ae6e2de599db1aa8fb  drive/MyDrive/binfo1-datapack1/read-counts.txt.summary
328883a73d507eafbf5b60bd6b906201  drive/MyDrive/binfo1-datapack1/RNA-control.bam
02073818e2f398a73c3b76e5169de1ca  drive/MyDrive/binfo1-datapack1/RNA-control.bam.bai
b09550d09d6c2a4ce27f0226f426fdb1  drive/MyDrive/binfo1-datapack1/RNA-siLin28a.bam
fef112c727244060ea62d3f2564a07f6  drive/MyDrive/binfo1-datapack1/RNA-siLin28a.bam.bai
28bbd0c47d725669340c784f1b772c01  drive/MyDrive/binfo1-datapack1/RNA-siLuc.bam
43590fdc4d81905c0432e0d1cb8cfd5b  drive/MyDrive/binfo1-datapack1/RNA-siLuc.bam.bai
5c08a9297307bc83259e658c4474f0cc  drive/MyDrive/binfo1-datapack1/RPF-siLin28a.bam
a1bb3e29be412dfd7fd8d16b1b1acc4c  drive/MyDrive/binfo1-datapack1/RPF-siLin28a.bam.bai
f2eebf50943024d0116c9cd3e744c707  drive/MyDrive/binfo1-datapack1/RPF-siLuc.bam
dc24f69e8f571fc8be30f28ce5b84fcd  drive/MyDrive/binfo1-datapack1/RPF-siLuc.bam.bai

In [3]:
!ls -al drive/MyDrive/binfo*

ls: drive/MyDrive/binfo1-datapack1: No such file or directory
lrw------- 1 root root    0 May 15 09:30 drive/MyDrive/binfo1-datapack1 -> /content/drive/.shortcut-targets-by-id/1QBJednh-C7A17PFOlpZHBKyDmBvd6klh/binfo1-datapack1

drive/MyDrive/binfo1-work:
total 7162852
-rw------- 1 root root 1370036258 May 15 09:33 CLIP-35L33G.bam
-rw------- 1 root root    3118336 May 15 09:33 CLIP-35L33G.bam.bai
-rw------- 1 root root       7113 May 15 09:39 CLIP-let7g.bam
-rw------- 1 root root      14561 May 15 09:47 CLIP-let7g-gene.pileup
-rw------- 1 root root    2685065 May 15 09:39 CLIP-let7g.pileup
-rw------- 1 root root  883334756 May 15 09:33 gencode.gtf
-rw------- 1 root root   24065406 May 15 09:33 read-counts.txt
-rw------- 1 root root        751 May 15 09:33 read-counts.txt.summary
-rw------- 1 root root 1003658801 May 15 09:33 RNA-control.bam
-rw------- 1 root root    2276104 May 15 09:34 RNA-control.bam.bai
-rw------- 1 root root 1260991122 May 15 09:34 RNA-siLin28a.bam
-rw------- 1 root root    2710744 May 15 09:34 RNA-siLin28a.bam.bai
-rw------- 1 root root  981684502 May 15 09:34 RNA-siLuc.bam
-rw------- 1 root root    2606104 May 15 09:34 RNA-siLuc.bam.bai
-rw------- 1 root root  737352902 May 15 09:34 RPF-siLin28a.bam
-rw------- 1 root root    2482768 May 15 09:34 RPF-siLin28a.bam.bai
-rw------- 1 root root 1055123479 May 15 09:34 RPF-siLuc.bam
-rw------- 1 root root    2605912 May 15 09:35 RPF-siLuc.bam.bai

# 파일 복사하기
첫 시간에 파일을 복사해 두었으면 이 부분은 생략하고 다음으로 넘어갑니다.

공유한 폴더를 나의 작업 폴더로 복사합니다.

In [ ]:
!mkdir -p /content/drive/MyDrive/binfo1-work
%cd /content/drive/MyDrive/binfo1-work
!cp ../binfo1-datapack1/* .

/content/drive/MyDrive/binfo1-work

# 프로그램 설치
데이터 준비가 끝났으면, 이제 이번 시간 실습에 필요한 프로그램들 몇 가지를 추가로 설치합니다.

In [4]:
!conda install -y bedtools bioawk samtools

Collecting package metadata (current_repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done
Solving environment: \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done

## Package Plan ##

  environment location: /root/conda

  added / updated specs:
    - bedtools
    - bioawk
    - samtools


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bedtools-2.26.0            |                0         739 KB  bioconda
    bioawk-1.0                 |       h5bf99c6_6         188 KB  bioconda
    c-ares-1.19.0              |       h5eee18b_0         118 KB
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    certifi-2023.5.7           |     pyhd8ed1ab_0         149 KB  conda-forge
    conda-23.3.1               |  py310hff52083_0         941 KB  conda-forge
    curl-7.87.0                |       h5eee18b_0          88 KB
    keyutils-1.6.1             |       h166bdaf_0         115 KB  conda-forge
    krb5-1.19.3                |       h3790be6_0         1.4 MB  conda-forge
    libcurl-7.87.0             |       h91b91d3_0         373 KB
    libedit-3.1.20191231       |       he28a2e2_2         121 KB  conda-forge
    libev-4.33                 |       h516909a_1         104 KB  conda-forge
    libgcc-7.2.0               |       h69d50b8_2         304 KB  conda-forge
    libnghttp2-1.46.0          |       hce63b2e_0         680 KB
    libssh2-1.10.0             |       ha56f1ee_2         233 KB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    samtools-1.6               |       hb116620_7         514 KB  bioconda
    ------------------------------------------------------------
                                           Total:         6.2 MB

The following NEW packages will be INSTALLED:

  bedtools           bioconda/linux-64::bedtools-2.26.0-0
  bioawk             bioconda/linux-64::bioawk-1.0-h5bf99c6_6
  c-ares             pkgs/main/linux-64::c-ares-1.19.0-h5eee18b_0
  curl               pkgs/main/linux-64::curl-7.87.0-h5eee18b_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  krb5               conda-forge/linux-64::krb5-1.19.3-h3790be6_0
  libcurl            pkgs/main/linux-64::libcurl-7.87.0-h91b91d3_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libgcc             conda-forge/linux-64::libgcc-7.2.0-h69d50b8_2
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.46.0-hce63b2e_0
  libssh2            conda-forge/linux-64::libssh2-1.10.0-ha56f1ee_2
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  samtools           bioconda/linux-64::samtools-1.6-hb116620_7

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2023.5.7-hbcca054_0
  certifi            pkgs/main/linux-64::certifi-2022.12.7~ --> conda-forge/noarch::certifi-2023.5.7-pyhd8ed1ab_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              pkgs/main::conda-23.3.1-py310h06a4308~ --> conda-forge::conda-23.3.1-py310hff52083_0



Downloading and Extracting Packages
curl-7.87.0          | 88 KB     | :   0% 0/1 [00:00<?, ?it/s]
bedtools-2.26.0      | 739 KB    | :   0% 0/1 [00:00<?, ?it/s]

certifi-2023.5.7     | 149 KB    | :   0% 0/1 [00:00<?, ?it/s]


libgcc-7.2.0         | 304 KB    | :   0% 0/1 [00:00<?, ?it/s]



bioawk-1.0           | 188 KB    | :   0% 0/1 [00:00<?, ?it/s]




keyutils-1.6.1       | 115 KB    | :   0% 0/1 [00:00<?, ?it/s]





libcurl-7.87.0       | 373 KB    | :   0% 0/1 [00:00<?, ?it/s]






c-ares-1.19.0        | 118 KB    | :   0% 0/1 [00:00<?, ?it/s]







samtools-1.6         | 514 KB    | :   0% 0/1 [00:00<?, ?it/s]








python_abi-3.10      | 4 KB      | :   0% 0/1 [00:00<?, ?it/s]









ca-certificates-2023 | 145 KB    | :   0% 0/1 [00:00<?, ?it/s]










libssh2-1.10.0       | 233 KB    | :   0% 0/1 [00:00<?, ?it/s]











libnghttp2-1.46.0    | 680 KB    | :   0% 0/1 [00:00<?, ?it/s]












conda-23.3.1         | 941 KB    | :   0% 0/1 [00:00<?, ?it/s]













libedit-3.1.20191231 | 121 KB    | :   0% 0/1 [00:00<?, ?it/s]














libev-4.33           | 104 KB    | :   0% 0/1 [00:00<?, ?it/s]















krb5-1.19.3          | 1.4 MB    | :   0% 0/1 [00:00<?, ?it/s]
bedtools-2.26.0      | 739 KB    | :   9% 0.08659733875976162/1 [00:00<00:01,  1.16s/it]



bioawk-1.0           | 188 KB    | :  17% 0.17021718690748908/1 [00:00<00:00,  1.69it/s]


curl-7.87.0          | 88 KB     | : 100% 1.0/1 [00:00<00:00,  7.11it/s]

certifi-2023.5.7     | 149 KB    | : 100% 1.0/1 [00:00<00:00,  6.47it/s]

certifi-2023.5.7     | 149 KB    | : 100% 1.0/1 [00:00<00:00,  6.47it/s]







samtools-1.6         | 514 KB    | :   3% 0.031138284467537997/1 [00:00<00:04,  5.10s/it]








python_abi-3.10      | 4 KB      | : 100% 1.0/1 [00:00<00:00,  5.97it/s]





libcurl-7.87.0       | 373 KB    | :   4% 0.042939961630796004/1 [00:00<00:03,  4.04s/it]




keyutils-1.6.1       | 115 KB    | :  14% 0.13904660063989951/1 [00:00<00:01,  1.32s/it]









ca-certificates-2023 | 145 KB    | :  11% 0.1104340792666487/1 [00:00<00:01,  1.80s/it]






c-ares-1.19.0        | 118 KB    | :  14% 0.13547773597387025/1 [00:00<00:01,  1.50s/it]










libssh2-1.10.0       | 233 KB    | :   7% 0.06874905587539233/1 [00:00<00:02,  3.07s/it]











libnghttp2-1.46.0    | 680 KB    | :   2% 0.023546353290151607/1 [00:00<00:09,  9.63s/it]



bioawk-1.0           | 188 KB    | : 100% 1.0/1 [00:00<00:00,  4.63it/s]



bioawk-1.0           | 188 KB    | : 100% 1.0/1 [00:00<00:00,  4.63it/s]













libedit-3.1.20191231 | 121 KB    | :  13% 0.13225915820403947/1 [00:00<00:01,  1.74s/it]












conda-23.3.1         | 941 KB    | :   2% 0.01699687325585979/1 [00:00<00:13, 13.71s/it]














libev-4.33           | 104 KB    | :  15% 0.1542894811187494/1 [00:00<00:01,  1.56s/it]















krb5-1.19.3          | 1.4 MB    | :   1% 0.010781401555880483/1 [00:00<00:22, 23.22s/it]


libgcc-7.2.0         | 304 KB    | : 100% 1.0/1 [00:00<00:00,  3.16it/s]


libgcc-7.2.0         | 304 KB    | : 100% 1.0/1 [00:00<00:00,  3.16it/s]








python_abi-3.10      | 4 KB      | : 100% 1.0/1 [00:00<00:00,  5.97it/s]
bedtools-2.26.0      | 739 KB    | : 100% 1.0/1 [00:00<00:00,  2.28it/s]
bedtools-2.26.0      | 739 KB    | : 100% 1.0/1 [00:00<00:00,  2.28it/s]







samtools-1.6         | 514 KB    | : 100% 1.0/1 [00:00<00:00,  2.40it/s]







samtools-1.6         | 514 KB    | : 100% 1.0/1 [00:00<00:00,  2.40it/s]









ca-certificates-2023 | 145 KB    | : 100% 1.0/1 [00:00<00:00,  2.33it/s]









ca-certificates-2023 | 145 KB    | : 100% 1.0/1 [00:00<00:00,  2.33it/s]





libcurl-7.87.0       | 373 KB    | : 100% 1.0/1 [00:00<00:00,  2.18it/s]





libcurl-7.87.0       | 373 KB    | : 100% 1.0/1 [00:00<00:00,  2.18it/s]




keyutils-1.6.1       | 115 KB    | : 100% 1.0/1 [00:00<00:00,  2.01it/s]




keyutils-1.6.1       | 115 KB    | : 100% 1.0/1 [00:00<00:00,  2.01it/s]






c-ares-1.19.0        | 118 KB    | : 100% 1.0/1 [00:00<00:00,  1.92it/s]






c-ares-1.19.0        | 118 KB    | : 100% 1.0/1 [00:00<00:00,  1.92it/s]













libedit-3.1.20191231 | 121 KB    | : 100% 1.0/1 [00:00<00:00,  1.72it/s]













libedit-3.1.20191231 | 121 KB    | : 100% 1.0/1 [00:00<00:00,  1.72it/s]














libev-4.33           | 104 KB    | : 100% 1.0/1 [00:00<00:00,  1.60it/s]














libev-4.33           | 104 KB    | : 100% 1.0/1 [00:00<00:00,  1.60it/s]










libssh2-1.10.0       | 233 KB    | : 100% 1.0/1 [00:00<00:00,  1.53it/s]










libssh2-1.10.0       | 233 KB    | : 100% 1.0/1 [00:00<00:00,  1.53it/s]











libnghttp2-1.46.0    | 680 KB    | : 100% 1.0/1 [00:00<00:00,  1.53it/s]











libnghttp2-1.46.0    | 680 KB    | : 100% 1.0/1 [00:00<00:00,  1.53it/s]












conda-23.3.1         | 941 KB    | : 100% 1.0/1 [00:01<00:00,  1.05it/s]












conda-23.3.1         | 941 KB    | : 100% 1.0/1 [00:01<00:00,  1.05it/s]















krb5-1.19.3          | 1.4 MB    | : 100% 1.0/1 [00:01<00:00,  1.10s/it]
























































































































































Preparing transaction: | done
Verifying transaction: - \ | done
Executing transaction: - \ | / - \ | / - \ | done

## Mission 3

이번 미션에서는 Figure S2A 아랫쪽에 표시되는 clustered error 분석 (CIMS; Crosslinking-induced mutation sites)을 합니다. 자외선에 의해서 단백질이 붙어있다가 단백질 분해효소로 단백질을 뜯어내고 남은 자리에서는 reverse-transcriptase가 오류를 자주 냅니다. 오류율을 분석해서 단백질이 앉아 있었던 자리를 분석해 봅시다.

데이터는 지난 번과 동일하기 때문에 이미 다운로드 받으셨다면 다시 다운로드 받을 필요는 없습니다.

In [5]:
%cd /content/drive/MyDrive/binfo1-work/

/content/drive/MyDrive/binfo1-work

Genome 전체로 계산하는 방법은 자원도 꽤 쓰고 시간이 걸리기 때문에 여기서는 유전자 단위로 간략하게 하도록 합시다. 예시로 Mirlet7g를 해 보고, 추가로 Mirlet7f-1과 Mirlet7d도 봐서 비교해 봅시다.

논문은 예전 레퍼런스 유전체인 mm9을 쓰고 있기 때문에, 현재 사용되는 레퍼런스 mm39와는 좌표계에 차이가 있습니다. 새로 annotation에서 위치를 찾습니다.

In [6]:
!grep -i mirlet7g gencode.gtf

chr9	ENSEMBL	gene	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; gene_type "miRNA"; gene_name "Mirlet7g"; level 3; mgi_id "MGI:2676800";
chr9	ENSEMBL	transcript	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; transcript_id "ENSMUST00000083506.3"; gene_type "miRNA"; gene_name "Mirlet7g"; transcript_type "miRNA"; transcript_name "Mirlet7g-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676800"; tag "basic";
chr9	ENSEMBL	exon	106056039	106056126	.	+	.	gene_id "ENSMUSG00000065440.3"; transcript_id "ENSMUST00000083506.3"; gene_type "miRNA"; gene_name "Mirlet7g"; transcript_type "miRNA"; transcript_name "Mirlet7g-201"; exon_number 1; exon_id "ENSMUSE00000522665.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676800"; tag "basic";

Splicing 되지 않는 transcript이기 때문에 결과가 단조롭습니다. 해당 좌표 범위로 bam을 솎아냅니다.

In [7]:
!samtools view -b -o CLIP-let7g.bam CLIP-35L33G.bam chr9:106056039-106056126
!samtools view CLIP-let7g.bam | wc -l

163

각 자리에 mapping된 read들의 분포를 요약하기 위해 samtools mpileup을 이용합니다. Shannon entropy를 구할 때는 reference를 따로 줄 필요는 없습니다. samtools를 쓰지 않고 직접 read를 분석하면 더욱 더 재미있습니다.

In [8]:
!samtools mpileup CLIP-let7g.bam > CLIP-let7g.pileup
!wc -l CLIP-let7g.pileup

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
68548 CLIP-let7g.pileup

Mirlet7g는 100bp도 안 되는 짧은 gene인데 `mpileup` 결과는 엄청 길게 나옵니다. 왜 그럴까요? (잘 한 번 생각해 봅시다)

이제 Mirlet7g의 핵심부분을 살펴봐서 어떻게 하면 좋을지 견적을 내 봅니다.

In [9]:
!head CLIP-let7g.pileup

chr9	106007092	N	9	^Ga^Ia^Ha^Ia^Ga^Ga^Ha^Ia^Ia	<IFIGGHII
chr9	106007093	N	9	ggggggggg	AFGIEGDII
chr9	106007094	N	9	ccccccccc	EHHIGAFEH
chr9	106007095	N	9	aaaaaaaaa	?HDIFA>II
chr9	106007096	N	9	aaaaaaaaa	EHHIG@CHH
chr9	106007097	N	9	ttttttttt	=HGEGDFII
chr9	106007098	N	9	aaaaaaaaa	?HHIGDEII
chr9	106007099	N	9	g-2nng-2nng-2nng-2nng-2nng-2nng-2nng-2nng-2nn	?IEHGEDII
chr9	106007100	N	9	*********	8IBIBC@EI
chr9	106007101	N	9	*********	8IBIBC@EI

In [10]:
!awk '$2 >= 106056039 && $2 <= 106056126 { print $0; }' CLIP-let7g.pileup > CLIP-let7g-gene.pileup
!tail CLIP-let7g-gene.pileup

chr9	106056117	N	138	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIHGHII:;HGIIDGGGIIBGEB?>H<GGIIIIDIIGFHIHH9IGG=GGHIDH?DGIBIIHHGGIEIGI8GIDHDG.GGHEDIIDIDGDHIDGIFGHG;DCDDHEE@I?CGG:IHGIBGIHIIDG@DHIGG
chr9	106056118	N	139	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIHGHII3AHIIIDGGGIIB3EHFBH>GIIIIIIIIIHIIHHAIIGBDGHIDH?GIIGIIHHDIIHIGIGGI=BGG9GIHHHIIGI=IAIIGGIEHGIEBG@DHDE;IBDGG4IGGIGGIIIIGGGDGIH1G
chr9	106056119	N	138	<<<<<<<<<TTTTTTTTTTTTTTTTTTTTTTTTTT$TTTT$TTTTTTTTTTTTTTT$TTTT$TTTTTTT$TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT	BHEIG?DIIGEFII:/GIIEDDHDIIF>BH3<HBEGIHIGFIIIBIIBE:HHGD>EGGDH7BIIGGIHHDHIHDEIGEIDHGG;GIHGHHIGD:IGHD:GGEHH?3G87HD</I=DGG=IHHIHBIFII@<HDHHH1G
chr9	106056120	N	133	<<<<<<<<<TTTTTTTTTTTTTTTTTTTTTTTTTTTT$TTTT$TTT$TTTTTTTTTT$TTTTTTTT$TTTTTTTTTTTT$T$TTTTTT$TTTT$TT$TTTTTTTTTTTTTTTTTTT$TTTTTTTTTTTTTTTTTTTTTTTTTTT	BHEIG?DIIHFBII74BIIIGDIIIIA8DHECHBIIIIIIIIHIIHB?IDGGGFDH?GIIIIHH@GHHGEDDGIEHBEDIHHGIIGI:HBII8DIIHHIBDD;<HDD3HB?@G?HHIIHIIIIIB@HDHDH8G
chr9	106056121	N	118	<<<<<<<<<GGGGGGGGGGGGGGGGGGGG$G$G$G$G$G$G$G$GGGGGG$GG$GGGG$GG$GGGG$G$GGG$GGG$GGG$GGGG$GGGGG$GGGGGGGGG$GGGGGG$GG$GGG$GGG$GGGG$G$GG$GGGGGG$GGGG$G$G$G$G$G$	BHEIG?DIIB<EDI/7BHHFB<FGHI3?GG>HAIHIFEF@H<<2>D3EE;HBAIIIBH4IHG@DI>G482GGFHID:I9II@BH@>HE8@;<HGI:GGBIDEIBIGIIIE?G@EIH7G
chr9	106056122	N	88	<<<<<<<<<C$C$C$C$C$C$C$C$C$C$C$C$C$CCCCCC$C$C$C$C$C$C$CCC$C$C$C$CC$C$CC$CC$C$C$C$C$C$C$C$C$C$C$C$C$C$CC$C$C$C$C$C$CC$CC$C$CCC$C$C$C$C$CCCCC$CCC$C	BHEIG?DIIEEGIIC;GIHEGBIIIIB1=FII?FEIGGGHDBIG=HHIIEBHD>EIHIG=I:HGBIIEF?E;DB3HB<GIHIHHEADF
chr9	106056123	N	31	<<<<<<<<<CCCCCCCCCCCCCCCCCCCCCC	BHEIG?DIIIIII>GIGGIGGD>BIHHHIEH
chr9	106056124	N	31	<<<<<<<<<AAAAAAAAAAAAAAAAAAAAAA	BHEIG?DIIIIHIGGIGGGIG:9DDBIEGFH
chr9	106056125	N	31	<<<<<<<<<GGGGGGGGGGGGGGGGGGGGGG	BHEIG?DIIIIIIGGE@GFIGD;GIGIIFHD
chr9	106056126	N	30	<<<<<<<<<GGGGGGGGGGGGGGGGGGGGG	BHEIG?DIIIIGHGHIGHI>G;GGGIGIHG

이제 pandas에 불러와서 분석해 봅니다. R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.

In [21]:
import pandas as pd

pileup = pd.read_csv('CLIP-let7g-gene.pileup', sep='\t', names=['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup.head()

  chrom        pos _ref  count  basereads      quals
0  chr9  106056039    N      9  <<<<<<<<<  BHEIG?DII
1  chr9  106056040    N      9  <<<<<<<<<  BHEIG?DII
2  chr9  106056041    N      9  <<<<<<<<<  BHEIG?DII
3  chr9  106056042    N      9  <<<<<<<<<  BHEIG?DII
4  chr9  106056043    N      9  <<<<<<<<<  BHEIG?DII

여기서 pileup에서 계산에 사용할 것은 match와 substitution만입니다. 나머지에 해당하는 tag들은 제거합니다.

R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.

In [22]:
import re
toremove = re.compile('[<>$*#^]')
pileup['matches'] = pileup['basereads'].apply(lambda x: toremove.sub('', x))

In [24]:
pileup=pileup[['chrom', 'pos', 'matches']]
pileup

   chrom        pos                                            matches
0   chr9  106056039
1   chr9  106056040
2   chr9  106056041
3   chr9  106056042
4   chr9  106056043
..   ...        ...                                                ...
83  chr9  106056122  CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...
84  chr9  106056123                             CCCCCCCCCCCCCCCCCCCCCC
85  chr9  106056124                             AAAAAAAAAAAAAAAAAAAAAA
86  chr9  106056125                             GGGGGGGGGGGGGGGGGGGGGG
87  chr9  106056126                              GGGGGGGGGGGGGGGGGGGGG

[88 rows x 3 columns]

In [25]:
pileup[pileup['pos'] == 106056094].iloc[0]['matches']

'GGGGGGAAAAAAAAGGGGGAAAAAAGCCGCAGGATGAGGTGATAAGGGAGGGGTGAAGGGCGGTGAAGGGGAAAAGAGAAAGAAAAATAAAGGGGGAGTGGGAGGAAGAAGAGAATA'

자 이제 데이터 준비가 대충 끝났습니다. 다음 순서로 진행해 보세요. (1-4번 단계는 R을 쓰시는 분들은 R로 보내서 작업하셔도 됩니다.)

1. 각 position별로 base수를 셉니다.
1. 각 position별로 Shannon entropy를 계산합니다.
1. 계산한 Shannon entropy를 [bedgraph format](https://genome.ucsc.edu/goldenPath/help/bedgraph.html)으로 출력합니다. 말은 복잡해도 실제로는 간단합니다. 4칸짜리를 만드시면 됩니다.
1. 결과 파일을 본인의 Google Drive에서 가져옵니다.
1. [UCSC Genome Browser](http://genome.ucsc.edu/cgi-bin/hgTracks?db=mm39&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr9%3A106056039-106056126)에 접속해서 Genome은 mm39로 선택합니다.
1. 그래프 아랫쪽의 add custom tracks 버튼을 누릅니다.
1. Paste URLs or data 옆의 Choose File 버튼을 누르고 우리가 만든 bedgraph 파일을 업로드 합니다.
1. 그리고 이리 저리 감상해 보다가 View 메뉴의 PDF/PS 를 눌러서 인증샷을 한 번 찍습니다.
1. Mirlet7d와 Mirlet7f-1도 한 번 해 봅니다.

In [28]:
base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
base_counts=base_counts.filter(items=['A','T','G','C'])
base_counts[['A', 'T', 'G', 'C']] = base_counts[['A', 'T', 'G', 'C']].fillna(0)
pileup = pd.concat([pileup.reset_index(drop=True), base_counts.reset_index(drop=True)], axis=1)
pileup

<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
<ipython-input-28-319e811cbb9a>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  base_counts = pileup['matches'].apply(lambda x: pd.Series(list(x)).value_counts())

,chrom,pos,matches,A,T,G,C
0,chr9,106056039,,0.0,0.0,0.0,0.0
1,chr9,106056040,,0.0,0.0,0.0,0.0
2,chr9,106056041,,0.0,0.0,0.0,0.0
3,chr9,106056042,,0.0,0.0,0.0,0.0
4,chr9,106056043,,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
83,chr9,106056122,CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...,0.0,0.0,0.0,79.0
84,chr9,106056123,CCCCCCCCCCCCCCCCCCCCCC,0.0,0.0,0.0,22.0
85,chr9,106056124,AAAAAAAAAAAAAAAAAAAAAA,22.0,0.0,0.0,0.0
86,chr9,106056125,GGGGGGGGGGGGGGGGGGGGGG,0.0,0.0,22.0,0.0
87,chr9,106056126,GGGGGGGGGGGGGGGGGGGGG,0.0,0.0,21.0,0.0

In [53]:
import numpy as np

import math

def shannon_entropy(row):
    counts = row[['A', 'T', 'G', 'C']].values
    total_count = counts.sum()
    if total_count > 0:
        p = counts / total_count
        p_nonzero = p[p != 0] 
        entropy = - (p_nonzero * np.array([math.log2(x) for x in p_nonzero])).sum()
    else:
        entropy = 0
    return entropy
pileup['entropy'] = pileup.apply(shannon_entropy, axis=1)
pileup['entropy'] = pileup['entropy'].replace(-0.000000, 0.000000)
pileup

,chrom,pos,matches,A,T,G,C,entropy
0,chr9,106056039,,0.0,0.0,0.0,0.0,0.0
1,chr9,106056040,,0.0,0.0,0.0,0.0,0.0
2,chr9,106056041,,0.0,0.0,0.0,0.0,0.0
3,chr9,106056042,,0.0,0.0,0.0,0.0,0.0
4,chr9,106056043,,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
83,chr9,106056122,CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...,0.0,0.0,0.0,79.0,0.0
84,chr9,106056123,CCCCCCCCCCCCCCCCCCCCCC,0.0,0.0,0.0,22.0,0.0
85,chr9,106056124,AAAAAAAAAAAAAAAAAAAAAA,22.0,0.0,0.0,0.0,0.0
86,chr9,106056125,GGGGGGGGGGGGGGGGGGGGGG,0.0,0.0,22.0,0.0,0.0
87,chr9,106056126,GGGGGGGGGGGGGGGGGGGGG,0.0,0.0,21.0,0.0,0.0

계산한 Shannon entropy를 bedgraph format으로 출력합니다. 말은 복잡해도 실제로는 간단합니다. 4칸짜리를 만드시면 됩니다

In [54]:
bedgraph = pileup[['chrom', 'pos', 'pos', 'entropy']].copy()
bedgraph.columns = ['chrom', 'start', 'end', 'value']
bedgraph.to_csv('shannon_entropy_mirlet7g.bedgraph', sep='\t', index=False, header=False)

mirlet7f-1

In [57]:
!grep -i 'mirlet7f-1' gencode.gtf

chr13	ENSEMBL	gene	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; level 3; mgi_id "MGI:2676798";
chr13	ENSEMBL	transcript	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; transcript_id "ENSMUST00000198652.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; transcript_type "miRNA"; transcript_name "Mirlet7f-1-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676798"; tag "basic";
chr13	ENSEMBL	exon	48691305	48691393	.	-	.	gene_id "ENSMUSG00000105621.3"; transcript_id "ENSMUST00000198652.3"; gene_type "miRNA"; gene_name "Mirlet7f-1"; transcript_type "miRNA"; transcript_name "Mirlet7f-1-201"; exon_number 1; exon_id "ENSMUSE00001348852.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676798"; tag "basic";

In [58]:
!samtools view -b -o CLIP-let7f_1.bam CLIP-35L33G.bam chr13:48691305-48691393
!samtools view CLIP-let7f_1.bam | wc -l

158

In [62]:
!samtools mpileup CLIP-let7f_1.bam > CLIP-let7f_1.pileup
!wc -l CLIP-let7f_1.pileup
!head CLIP-let7f_1.pileup

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
97 CLIP-let7f_1.pileup
chr13	48691290	N	1	^Gg	A
chr13	48691291	N	26	c^Hc^Ic^Dc^Hc^Gc^Ic^Gc^Ic^Gc^Ic^Ic^Hc^Hc^Hc^Ec^Ic^Ic^Ic^Hc^Hc^Hc^Ic^Ic^Ic^Hc	DDI4G>I@H;GGGFH7IHIHHHFIIG
chr13	48691292	N	25	aaaaaaaaaaaaaaaaaaaaaaaaa	DGIG>IBI?IIGHH7HIEHFFGHIG
chr13	48691293	N	38	gggggggggggggggggggggggggg^Ig^Hg^Ig^Ig^Ig^Ig^Hg^Ig^Ig^Dg^Ig^Ig	DGI4>AIGIBIIGGE/IIIDGHIIIHEGIHIIBIIBII
chr13	48691294	N	49	cccccccccccccccccccccccccccccccccccccc^Ec^Hc^Ic^Hc^Hc^Gc^Ic^Ic^Gc^Ic^Hc	?>I1E5IDG<I>EHH7IIIFHHEIHGCEDIHIEHG?II3BIDD7IHGGH
chr13	48691295	N	58	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ha^Ia^Ha^Ha^Ha^Ia^Ia^Ia^Ha	BDI?HBIGHGIHGHG7IIIGBGIIIGBEFIIIBIH=II=EIGA6IHGIHDIHGGIII0
chr13	48691296	N	81	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ia^Da^Ia^Ha^Ia^Ha^Ga^Ha^Ha^Ga^Ia^Ha^Ha^Ia^Ha^Ha^Ia^Ha^Ia^Ga^Ia^Ga	<GI7H?IGIEIIGHG;FIIGGHIIIGIBGDIHGII@II9FHDA9IIGGHGIEGGIIIBEIBIHIG;DG?IBHICGIHI6I;
chr13	48691297	N	80	gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg	8EI.HBIGIGIGGHG1IIIGGGIIIEIBGGIIDII=II=FIGD5IIGDHDIHGGIGH@DIDGDIB1GGDIHGD=EHHGH5
chr13	48691298	N	80	tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt	GI4H7IGIGIIGHG7IHIGDHIGIGIBGGHIDIH@II?EIGG=IIGIHDGHG8IFH7DH@HHIG1GH9HDHI<GIDB.H/
chr13	48691299	N	80	cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc	<<I7H=I@I;IHGGG7HIIGGHGGHGFEBIEIDII=II:HIC><IIGIHGHGEGIII;HGBIHGD;GF<IGHICEIDII4

In [61]:
!awk '$2 >= 48691305&& $2 <= 48691393  { print $0; }' CLIP-let7f_1.pileup > CLIP-let7f_1-gene.pileup
!tail CLIP-let7f_1-gene.pileup

chr13	48691377	N	24	tttttttttttttttttttttttt	BIIGIGEDCGFIFGI@GHIDDIGI
chr13	48691378	N	24	aaaaaaaaaaaaaaaaaaaaaaaa	?HIFIGGGAFEFABI>GII;EIGI
chr13	48691379	N	24	cccccccccccccccccccccccc	EIIGIGGDEGGIEGI;GIIDDIGI
chr13	48691380	N	24	tttttttttttttttttttttttt	EIIGIBGGEGFIFGI@GIIBDIGI
chr13	48691381	N	24	aaaaaaaaaaaaaaaaaaaaaaaa	BEHFIGEG@FCEAGH4GII;AIDH
chr13	48691382	N	24	cccccccccccccccccccccccc	?IEGIHGG?GEGEBI=GIIDEIGG
chr13	48691383	N	24	cccccccccccccccccccccccc	EIGGIGGGAGFGFGI=GIIDGIGG
chr13	48691384	N	24	tttttttttttttttttttttttt	<IGGIHGG>GEGBGI8GII@GIGG
chr13	48691385	N	24	cccccccccccccccccccccccc	BIGGIBDD?GEGBEI=GIIBGIGG
chr13	48691386	N	24	a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$a$	EIGGIFDECGFGFGI2BIIDGIGG

In [63]:
pileup_f1 = pd.read_csv('CLIP-let7f_1-gene.pileup', sep='\t', names=['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup_f1.head()

,chrom,pos,_ref,count,basereads,quals
0,chr13,48691305,N,109,cccccccccccccccccccccccccccccccccccccccccccccc...,B?IBHBIGI>GGHHH:IIHFGGIIIGHHIHIIBIG?IGBFIE>@II...
1,chr13,48691306,N,109,tttttttttttttttttttttttttttttttttttttttttttttt...,=GH0H=IBI>IHHGH?IIIGGHBII@HHIGHIDIIIGDHIFGEIHG...
2,chr13,48691307,N,109,cccccccccccccccccccccccccccccccccccccccccccccc...,;GIBH=IGIAEHH:H:IIIHEHIIIEIDHHIIGII:IIDBI<>GII...
3,chr13,48691308,N,109,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,AGI?H6IGI?IHHHHBIIIHEHHIIGIHIIIIGII<IIDFIEE<II...
4,chr13,48691309,N,109,gggggggggggggggggggggggggggggggggggggggggggggg...,>EI>F=IDGEIIHHGBIIIHHHIIIGIHHHIIDII:II5HIGG@II...

In [64]:
toremove = re.compile('[<>$*#^]')
pileup_f1['matches'] = pileup_f1['basereads'].apply(lambda x: toremove.sub('', x))

In [65]:
pileup_f1=pileup_f1[['chrom', 'pos', 'matches']]
pileup_f1

    chrom       pos                                            matches
0   chr13  48691305  cccccccccccccccccccccccccccccccccccccccccccccc...
1   chr13  48691306  tttttttttttttttttttttttttttttttttttttttttttttt...
2   chr13  48691307  cccccccccccccccccccccccccccccccccccccccccccccc...
3   chr13  48691308  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
4   chr13  48691309  gggggggggggggggggggggggggggggggggggggggggggggg...
..    ...       ...                                                ...
77  chr13  48691382                           cccccccccccccccccccccccc
78  chr13  48691383                           cccccccccccccccccccccccc
79  chr13  48691384                           tttttttttttttttttttttttt
80  chr13  48691385                           cccccccccccccccccccccccc
81  chr13  48691386                           aaaaaaaaaaaaaaaaaaaaaaaa

[82 rows x 3 columns]

In [67]:
base_counts = pileup_f1['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
base_counts=base_counts.filter(items=['a','t','g','c'])
base_counts[['a', 't', 'g', 'c']] = base_counts[['a', 't', 'g', 'c']].fillna(0)
pileup_f1 = pd.concat([pileup_f1.reset_index(drop=True), base_counts.reset_index(drop=True)], axis=1)
pileup_f1

,chrom,pos,matches,a,t,g,c
0,chr13,48691305,cccccccccccccccccccccccccccccccccccccccccccccc...,0.0,0.0,0.0,109.0
1,chr13,48691306,tttttttttttttttttttttttttttttttttttttttttttttt...,0.0,109.0,0.0,0.0
2,chr13,48691307,cccccccccccccccccccccccccccccccccccccccccccccc...,0.0,0.0,0.0,109.0
3,chr13,48691308,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,109.0,0.0,0.0,0.0
4,chr13,48691309,gggggggggggggggggggggggggggggggggggggggggggggg...,0.0,0.0,109.0,0.0
...,...,...,...,...,...,...,...
77,chr13,48691382,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0
78,chr13,48691383,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0
79,chr13,48691384,tttttttttttttttttttttttt,0.0,24.0,0.0,0.0
80,chr13,48691385,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0
81,chr13,48691386,aaaaaaaaaaaaaaaaaaaaaaaa,24.0,0.0,0.0,0.0

In [71]:
import numpy as np

import math

def shannon_entropy(row):
    counts = row[['a', 't', 'g', 'c']].values
    total_count = counts.sum()
    if total_count > 0:
        p = counts / total_count
        p_nonzero = p[p != 0] 
        entropy = - (p_nonzero * np.array([math.log2(x) for x in p_nonzero])).sum()
    else:
        entropy = 0
    return entropy
pileup_f1['entropy'] = pileup_f1.apply(shannon_entropy, axis=1)
pileup_f1['entropy'] = pileup_f1['entropy'].replace(-0.000000, 0.000000)
pileup_f1

,chrom,pos,matches,a,t,g,c,entropy
0,chr13,48691305,cccccccccccccccccccccccccccccccccccccccccccccc...,0.0,0.0,0.0,109.0,0.0
1,chr13,48691306,tttttttttttttttttttttttttttttttttttttttttttttt...,0.0,109.0,0.0,0.0,0.0
2,chr13,48691307,cccccccccccccccccccccccccccccccccccccccccccccc...,0.0,0.0,0.0,109.0,0.0
3,chr13,48691308,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,109.0,0.0,0.0,0.0,0.0
4,chr13,48691309,gggggggggggggggggggggggggggggggggggggggggggggg...,0.0,0.0,109.0,0.0,0.0
...,...,...,...,...,...,...,...,...
77,chr13,48691382,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0,0.0
78,chr13,48691383,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0,0.0
79,chr13,48691384,tttttttttttttttttttttttt,0.0,24.0,0.0,0.0,0.0
80,chr13,48691385,cccccccccccccccccccccccc,0.0,0.0,0.0,24.0,0.0
81,chr13,48691386,aaaaaaaaaaaaaaaaaaaaaaaa,24.0,0.0,0.0,0.0,0.0

In [72]:
bedgraph = pileup_f1[['chrom', 'pos', 'pos', 'entropy']].copy()
bedgraph.columns = ['chrom', 'start', 'end', 'value']
bedgraph.to_csv('shannon_entropy_mirlet7f_1.bedgraph', sep='\t', index=False, header=False)

In [74]:
!grep -i mirlet7d gencode.gtf

chr13	ENSEMBL	gene	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; gene_type "miRNA"; gene_name "Mirlet7d"; level 3; mgi_id "MGI:2676796";
chr13	ENSEMBL	transcript	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";
chr13	ENSEMBL	exon	48689488	48689590	.	-	.	gene_id "ENSMUSG00000065453.3"; transcript_id "ENSMUST00000083519.3"; gene_type "miRNA"; gene_name "Mirlet7d"; transcript_type "miRNA"; transcript_name "Mirlet7d-201"; exon_number 1; exon_id "ENSMUSE00000522678.2"; level 3; transcript_support_level "NA"; mgi_id "MGI:2676796"; tag "basic";

In [76]:
!samtools view -b -o CLIP-let7d.bam CLIP-35L33G.bam chr13:48689488-48689590
!samtools view CLIP-let7d.bam | wc -l

187

In [77]:
!samtools mpileup CLIP-let7d.bam > CLIP-let7d.pileup
!wc -l CLIP-let7d.pileup

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
87 CLIP-let7d.pileup

In [78]:
!awk '$2 >= 48689488 && $2 <= 48689590 { print $0; }' CLIP-let7d.pileup > CLIP-let7d-gene.pileup
!tail CLIP-let7d-gene.pileup

chr13	48689565	N	6	cccccc	>IGIIH
chr13	48689566	N	6	tttttt	:IGFIH
chr13	48689567	N	6	aaaaaa	8IFIFI
chr13	48689568	N	6	cccccc	?IGIII
chr13	48689569	N	6	tttttt	;IGIII
chr13	48689570	N	5	aaaaa	EDECD
chr13	48689571	N	6	cccccc	:GGIGG
chr13	48689572	N	6	cccccc	:GGIGG
chr13	48689573	N	6	tttttt	5GGIGG
chr13	48689574	N	6	c$c$c$c$c$c$	;GGIGG

In [80]:
pileup_d = pd.read_csv('CLIP-let7d-gene.pileup', sep='\t', names=['chrom', 'pos', '_ref', 'count', 'basereads', 'quals'])
pileup_d

,chrom,pos,_ref,count,basereads,quals
0,chr13,48689488,N,24,^Ga^Ia^Ha^Ia^Ha^Ia^Ia^Ia^Ga^Ia^Ia^Ia^Ia^Ia^Ha^...,BIHGGIHIEIIIGIHIGEGH5BDD
1,chr13,48689489,N,53,aaaaaaaaaaaaaaaaaaaaaaaaa^Ia^Ha^Ia^Ga^Ga^Ha^Ia...,GIHIGIIIEIIIIIHIG>EB4@5HDIHIBEGIID?IIGII@H>IGH...
2,chr13,48689490,N,69,tttttttttttttttttttttttttttttttttttttttttttttt...,GIHIGHIFFIIIIIFHGEDG;2>FDIHIDGBIIDBIIDIIAH>IBG...
3,chr13,48689491,N,105,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,EIGHEHHIEIIIIIHIGCBH:?>HGGHI>GBIIGBIIGIHBB;IHI...
4,chr13,48689492,N,105,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,GIGIEIEI7IIIGIGIG;?F:D@G7GHIAGAIIG3IIGIHDB2IHI...
...,...,...,...,...,...,...
82,chr13,48689570,N,5,aaaaa,EDECD
83,chr13,48689571,N,6,cccccc,:GGIGG
84,chr13,48689572,N,6,cccccc,:GGIGG
85,chr13,48689573,N,6,tttttt,5GGIGG
86,chr13,48689574,N,6,c$c$c$c$c$c$,;GGIGG

In [81]:
toremove = re.compile('[<>$*#^]')
pileup_d['matches'] = pileup_d['basereads'].apply(lambda x: toremove.sub('', x))

In [82]:
pileup_d=pileup_d[['chrom', 'pos', 'matches']]
pileup_d

    chrom       pos                                            matches
0   chr13  48689488   GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa
1   chr13  48689489  aaaaaaaaaaaaaaaaaaaaaaaaaIaHaIaGaGaHaIaIaGaGaI...
2   chr13  48689490  tttttttttttttttttttttttttttttttttttttttttttttt...
3   chr13  48689491  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
4   chr13  48689492  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
..    ...       ...                                                ...
82  chr13  48689570                                              aaaaa
83  chr13  48689571                                             cccccc
84  chr13  48689572                                             cccccc
85  chr13  48689573                                             tttttt
86  chr13  48689574                                             cccccc

[87 rows x 3 columns]

In [83]:
base_counts = pileup_d['matches'].apply(lambda x: pd.Series(list(x)).value_counts())
base_counts=base_counts.filter(items=['a','t','g','c'])
base_counts[['a', 't', 'g', 'c']] = base_counts[['a', 't', 'g', 'c']].fillna(0)
pileup_d = pd.concat([pileup_d.reset_index(drop=True), base_counts.reset_index(drop=True)], axis=1)
pileup_d

,chrom,pos,matches,a,t,g,c
0,chr13,48689488,GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa,24.0,0.0,0.0,0.0
1,chr13,48689489,aaaaaaaaaaaaaaaaaaaaaaaaaIaHaIaGaGaHaIaIaGaGaI...,53.0,0.0,0.0,0.0
2,chr13,48689490,tttttttttttttttttttttttttttttttttttttttttttttt...,0.0,69.0,0.0,0.0
3,chr13,48689491,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,105.0,0.0,0.0,0.0
4,chr13,48689492,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,105.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
82,chr13,48689570,aaaaa,5.0,0.0,0.0,0.0
83,chr13,48689571,cccccc,0.0,0.0,0.0,6.0
84,chr13,48689572,cccccc,0.0,0.0,0.0,6.0
85,chr13,48689573,tttttt,0.0,6.0,0.0,0.0
86,chr13,48689574,cccccc,0.0,0.0,0.0,6.0

In [84]:
import numpy as np

import math

def shannon_entropy(row):
    counts = row[['a', 't', 'g', 'c']].values
    total_count = counts.sum()
    if total_count > 0:
        p = counts / total_count
        p_nonzero = p[p != 0] 
        entropy = - (p_nonzero * np.array([math.log2(x) for x in p_nonzero])).sum()
    else:
        entropy = 0
    return entropy
pileup_d['entropy'] = pileup_d.apply(shannon_entropy, axis=1)
pileup_d['entropy'] = pileup_d['entropy'].replace(-0.000000, 0.000000)
pileup_d

,chrom,pos,matches,a,t,g,c,entropy
0,chr13,48689488,GaIaHaIaHaIaIaIaGaIaIaIaIaIaHaIaGaGaGaIaEaDaHaGa,24.0,0.0,0.0,0.0,0.0
1,chr13,48689489,aaaaaaaaaaaaaaaaaaaaaaaaaIaHaIaGaGaHaIaIaGaGaI...,53.0,0.0,0.0,0.0,0.0
2,chr13,48689490,tttttttttttttttttttttttttttttttttttttttttttttt...,0.0,69.0,0.0,0.0,0.0
3,chr13,48689491,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,105.0,0.0,0.0,0.0,0.0
4,chr13,48689492,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,105.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
82,chr13,48689570,aaaaa,5.0,0.0,0.0,0.0,0.0
83,chr13,48689571,cccccc,0.0,0.0,0.0,6.0,0.0
84,chr13,48689572,cccccc,0.0,0.0,0.0,6.0,0.0
85,chr13,48689573,tttttt,0.0,6.0,0.0,0.0,0.0
86,chr13,48689574,cccccc,0.0,0.0,0.0,6.0,0.0

In [87]:
bedgraph = pileup_d[['chrom', 'pos', 'pos', 'entropy']].copy()
bedgraph.columns = ['chrom', 'start', 'end', 'value']
bedgraph.to_csv('shannon_entropy_mirlet7d.bedgraph', sep='\t', index=False, header=False)